// React
import { useEffect, useState } from 'react';

// Next
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

// Libraries
import { signIn, signOut } from 'next-auth/react';
import { useSession } from 'next-auth/react';

// MUI
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardActions from '@mui/material/CardActions';
import Typography from '@mui/material/Typography';

const Home: NextPage = () => {
  const { status } = useSession();
  const router = useRouter();

  const [isRedirecting, setIsRedirecting] = useState(false);

  useEffect(() => {
    if (status === 'authenticated' && router && !isRedirecting) {
      setIsRedirecting(true);
      router.push('/students');
    }
  }, [status, router, isRedirecting]);

  if (status === 'loading') {
    return <div>Loading</div>;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <Card sx={{ maxWidth: 500, margin: 'auto', flexGrow: 1 }}>
          <CardContent>
            <Typography variant="h1" align="center" sx={{ fontSize: '2.2rem', marginBottom: '1.5rem' }}>
              Invoice Generator
            </Typography>
            <Typography variant="body1" align="center">
              Designed to make handling a large studio of private lesson students easier. Manage your students info and
              generate monthly lesson invoices to get paid on time.
            </Typography>
          </CardContent>
          <CardActions sx={{ marginBottom: '1rem' }}>
            <Button variant="outlined" onClick={() => signIn()} sx={{ margin: 'auto' }}>
              Sign In
            </Button>
          </CardActions>
        </Card>
      </Container>
    </div>
  );
};

export default Home;
